# Generated by Django 6.0.1 on 2026-01-27 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('indigena', 'Indígena'), ('afro', 'Afrodescendiente'), ('campesina', 'Campesina')], max_length=20)),
                ('resena_cultural', models.TextField()),
                ('historia', models.TextField()),
                ('logo_o_emblema', models.ImageField(blank=True, null=True, upload_to='comunidades/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='comunidades/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='comunidades.comunidad')),
            ],
        ),
    ]
