# Generated by Django 6.0.1 on 2026-01-31 06:45

import suarez.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0002_comunidad_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagencomunidad',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/galeria/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='logo_o_emblema',
            field=suarez.image_optimizer.OptimizedImageField(default=1, help_text='Logo o emblema de la comunidad', upload_to='comunidades/logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagencomunidad',
            name='imagen',
            field=suarez.image_optimizer.OptimizedImageField(upload_to='comunidades/galeria/'),
        ),
    ]
