# Generated by Django 5.1.2 on 2026-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0003_imagencomunidad_imagen_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='video_url',
            field=models.URLField(blank=True, help_text='Enlace de YouTube o Vimeo', max_length=500, null=True),
        ),
    ]
