# Generated by Django 6.0.1 on 2026-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Bienvenidos a Suárez', max_length=200)),
                ('subtitulo', models.TextField(default='Portal Institucional de la Alcaldía Municipal.')),
                ('imagen_fondo', models.ImageField(help_text='Imagen de gran tamaño para el fondo del banner', upload_to='banner/')),
                ('texto_boton', models.CharField(default='Ver Noticias', max_length=50)),
                ('link_boton', models.CharField(default='/noticias/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner Principal',
                'verbose_name_plural': 'Banner Principal',
            },
        ),
        migrations.AddField(
            model_name='imagengaleria',
            name='es_destacada',
            field=models.BooleanField(default=False, help_text='Si se marca, aparecerá en el carrusel de la página de inicio'),
        ),
    ]
