# Generated by Django 6.0.1 on 2026-01-31 06:45

import suarez.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_bannerprincipal_imagengaleria_es_destacada'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodestacado',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_destacados/thumbnails/'),
        ),
        migrations.AddField(
            model_name='imagengaleria',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='bannerprincipal',
            name='imagen_fondo',
            field=suarez.image_optimizer.OptimizedImageField(help_text='Imagen de gran tamaño para el fondo del banner', upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='eventodestacado',
            name='imagen',
            field=suarez.image_optimizer.OptimizedImageField(upload_to='eventos_destacados/'),
        ),
        migrations.AlterField(
            model_name='imagengaleria',
            name='imagen',
            field=suarez.image_optimizer.OptimizedImageField(upload_to='galeria/'),
        ),
    ]
