# Generated by Django 6.0.1 on 2026-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_eventodestacado_imagen_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerprincipal',
            name='subtitulo',
            field=models.TextField(default='Portal de la Tradición y Cultura Cafetera.'),
        ),
    ]
