# Generated by Django 6.0.1 on 2026-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaCafetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('historia', models.TextField()),
                ('proceso', models.TextField(help_text='Descripción del proceso de producción o preparación')),
                ('imagen_principal', models.ImageField(upload_to='cafe/imagenes/')),
                ('video_url', models.URLField(blank=True, help_text='URL de video relacionado', null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
