# Generated by Django 6.0.1 on 2026-01-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias_cafeteras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciacafetera',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
