# Generated by Django 6.0.1 on 2026-01-31 06:45

import suarez.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias_cafeteras', '0002_experienciacafetera_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciacafetera',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cafe/imagenes/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='experienciacafetera',
            name='imagen_principal',
            field=suarez.image_optimizer.OptimizedImageField(upload_to='cafe/imagenes/'),
        ),
    ]
