# Generated by Django 5.1.2 on 2026-03-22 06:15

import django.db.models.deletion
import suarez.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencias_cafeteras', '0003_experienciacafetera_imagen_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienciacafetera',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RemoveField(
            model_name='experienciacafetera',
            name='historia',
        ),
        migrations.RemoveField(
            model_name='experienciacafetera',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='experienciacafetera',
            name='video_url',
        ),
        migrations.AddField(
            model_name='experienciacafetera',
            name='descripcion_breve',
            field=models.TextField(blank=True, help_text='Descripción breve para la lista', null=True),
        ),
        migrations.AlterField(
            model_name='experienciacafetera',
            name='imagen_principal',
            field=suarez.image_optimizer.OptimizedImageField(blank=True, null=True, upload_to='cafe/imagenes/'),
        ),
        migrations.AlterField(
            model_name='experienciacafetera',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ContenidoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('video', 'Video'), ('imagen', 'Imagen')], max_length=10)),
                ('orden', models.IntegerField(default=0, help_text='Orden de presentación (menor número = primero)')),
                ('titulo_bloque', models.CharField(blank=True, help_text='Opcional: Título para esta sección o bloque', max_length=200, null=True)),
                ('contenido_texto', models.TextField(blank=True, help_text='Contenido del texto (si el tipo es Texto)', null=True)),
                ('url_video', models.URLField(blank=True, help_text='URL de YouTube o Vimeo', null=True)),
                ('imagen', suarez.image_optimizer.OptimizedImageField(blank=True, null=True, upload_to='cafe/galeria/')),
                ('descripcion_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido', to='experiencias_cafeteras.experienciacafetera')),
            ],
            options={
                'verbose_name': 'Contenido de Experiencia',
                'verbose_name_plural': 'Contenido de Experiencias',
                'ordering': ['experiencia', 'orden', '-fecha_creacion'],
            },
        ),
    ]
