# Generated by Django 6.0.1 on 2026-01-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Identificador único para la URL (ej. nueva-obra-en-el-pueblo)', unique=True)),
                ('contenido', models.TextField()),
                ('imagen_destacada', models.ImageField(upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('es_evento', models.BooleanField(default=False, help_text='Marcar si es un evento municipal')),
                ('fecha_evento', models.DateField(blank=True, help_text='Solo si es un evento', null=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
