# Generated by Django 6.0.1 on 2026-01-31 06:45

import suarez.image_optimizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_destacada',
            field=suarez.image_optimizer.OptimizedImageField(upload_to='noticias/'),
        ),
    ]
